---
- name: Install terminal packages
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: "{{ 'latest' if install_latest_packages else 'present' }}"
  loop:
    - "wezterm"
    - "nerd-fonts-meslo"

- name: Copy dotfiles
  ansible.windows.win_copy:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    remote_src: true
  loop: "{{ windows_terminal }}"
