---
terminal_symlinks:
  # git
  - source: ${HOME}/macos-setup/dotfiles/git/.gitconfig
    dest: "{{ ansible_env.USERPROFILE }}\\.gitconfig"
  - source: ${HOME}/macos-setup/dotfiles/git/.gitignore_global
    dest: "{{ ansible_env.USERPROFILE }}\\.gitignore_global"
  - source: ${HOME}/macos-setup/dotfiles/git/.gitmessage
    dest: "{{ ansible_env.USERPROFILE }}\\.gitmessage"

  # wezterm
  - source: ${HOME}/macos-setup/dotfiles/config/wezterm/windows_wezterm.lua
    dest: "{{ ansible_env.USERPROFILE }}\\.wezterm.lua"
