---
# Homebrew packages
- name: Update homebrew index
  community.general.homebrew:
    update_homebrew: true

- name: Import terminal setup tasks
  ansible.builtin.import_tasks:
    file: tasks/terminal.yml

# Homebrew casks
- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - "1password"
    - "affinity-designer"
    - "affinity-photo"
    - "affinity-publisher"
    - "alacritty"
    - "aldente"
    - "appcleaner"
    - "arc"
    - "boosteroid"
    - "betterdisplay"
    - "db-browser-for-sqlite"
    - "devtoys"
    - "docker"
    - "github"
    - "hiddenbar"
    - "iterm2"
    - "keyboardcleantool"
    - "mullvadvpn"
    - "obs"
    - "obsidian"
    - "openinterminal"
    - "parallels@19"
    - "postman"
    - "raspberry-pi-imager"
    - "raycast"
    - "scroll-reverser"
    - "signal"
    - "slack"
    - "spotify"
    - "sublime-text"
    - "synology-drive"
    - "updf"
    - "visual-studio-code"
    - "vlc"
    - "vnc-viewer"
    - "wezterm"
  tags:
    - ignore-vm

- name: Install mas
  community.general.homebrew:
    name: "mas"
    state: present

- name: Upgrade homebrew packages
  community.general.homebrew:
    upgrade_all: true
  when: package_install_latest

# App Store
- name: Install app store apps.  # noqa: args[module]
  community.general.mas:
    id: "{{ item | int }}"
    state: present
  loop:
    - 424390742  # Compressor
    - 424389933  # Final Cut Pro
    - 409183694  # Keynote
    - 441258766  # Magnet
    - 434290957  # Motion
    - 409203825  # Numbers
    - 409201541  # Pages
    - 1295203466  # Microsoft Remote Desktop
    - 497799835  # Xcode
    # Safari Extensions
    - 1569813296  # 1Password for Safari
    - 1440147259  # AdGuard for Safari
    - 1521133201  # Speed Player for Safari
    - 1573461917  # SponsorBlock for YouTube
  tags:
    - ignore-vm

- name: Upgrade app store apps
  community.general.mas:
    upgrade_all: true
  when: package_install_latest

- name: Install nerd font macOS
  community.general.homebrew_cask:
    name: "font-meslo-lg-nerd-font"
    state: present

# Create program symlinks.
- name: Ensure symlink directories exist
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: "0775"
  loop: "{{ program_symlinks }}"

- name: Create dotfile symlinks
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ program_symlinks }}"
