---
- name: Ensure symlink directories exist.
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: "0775"
  loop: "{{ dotfile_symlinks }}"

- name: Create dotfile symlinks.
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ dotfile_symlinks }}"

