---
# https://macos-defaults.com/

- name: Finder show file extension
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllExtensions
    value: true
    type: bool

- name: Finder show all files
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    value: true
    type: bool

- name: Finder search current folder by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    value: SCcf
    type: string

- name: Finder warning when changing file extension
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    value: true
    type: bool

- name: Finder show items in column view
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    value: clmv
    type: string

- name: Quit Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    value: true
    type: bool

- name: Finder show path bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    value: true
    type: bool

- name: Finder show status bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    value: true
    type: bool

- name: Finder do not remove items from trash after 30 days
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXRemoveOldTrashItems
    value: false
    type: bool

- name: Finder default new windows and tabs
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    value: PfDo
    type: string

- name: Finder default location
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    # TODO: Make this correctpond to darwin-system.nix
    value: "file://Users/{{ lookup('env','USER') }}/Documents/"
    type: string

- name: Finder show external disks on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    value: true
    type: bool

- name: Finder show hard disks on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    value: false
    type: bool

- name: Remove all tags from sidebar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    value: false
    type: bool

- name: Finder show tool bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowToolbar
    value: true
    type: bool

- name: Finder show warning before emptying trash
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    value: false
    type: bool
