---
- name: Finder show all files.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    value: true
    type: bool

# Finder general settings
- name: Finder show hard disks on desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    value: true
    type: bool

- name: Finder show external disks on desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    value: true
    type: bool

- name: Finder default location.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    value: "file://${HOME}/Documents/"
    type: string

- name: Finder default new windows and tabs.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    value: "PfDo"
    type: string

# Finder advanced settings
- name: Finder show file extension.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    value: true
    type: bool

- name: Finder show warning before changing extension.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    value: true
    type: bool

- name: Finder show warning before removing from iCloud Drive.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableRemoveFromICloudDriveWarning
    value: true
    type: bool

- name: Finder show warning before emptying trash.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    value: true
    type: bool

- name: Finder do not remove items from trash after 30 days.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXRemoveOldTrashItems
    value: false
    type: bool

- name: Finder search current folder by default.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    value: SCcf
    type: string

# Finder tags settings
- name: Remove all tags from sidebar.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    value: false
    type: bool

# Finder view settings
- name: Finder show tool bar.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowToolbar
    value: true
    type: bool

- name: Finder show path bar.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    value: true
    type: bool

- name: Finder show status bar.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    value: true
    type: bool

# Reload finder.
- name: Reload finder.
  ansible.builtin.command: >
    killall Finder
  changed_when: false
