---
- name: Install homebrew packages.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
    upgrade_all: "{{ packages_upgrade_packages }}"
  loop:
    - "dockutil"
    - "doctl"
    - "git"
    - "pyenv"
    - "htop"
    - "mas"
    - "tmux"
    - "tree"
    - "zbar"

- name: Install homebrew casks.
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    update_homebrew: true
    upgrade_all: "{{ packages_upgrade_packages }}"
  loop:
    - "1password"
    - "arc"
    - "mullvadvpn"
    - "obsidian"
    - "signal"
    - "slack"
    - "spotify"
    # - "db-browser-for-sqlite"
    - "docker"
    - "dotnet-sdk"
    - "github"
    - "iterm2"
    - "parallels"
    - "postman"
    - "raspberry-pi-imager"
    - "sublime-text"
    - "vagrant-vmware-utility"
    - "vagrant"
    - "visual-studio-code"
    - "vmware-fusion"
    - "vnc-viewer"
    - "aldente"
    - "appcleaner"
    - "hiddenbar"
    - "monitorcontrol"
    - "obs"
    - "openinterminal"
    - "scroll-reverser"
    - "synology-drive"
    - "vlc"
    - "affinity-designer"
    - "affinity-photo"
    - "affinity-publisher"
    - "updf"

- name: Install app store apps.  # noqa: args[module]
  community.general.mas:
    id: "{{ item | int }}"
    state: present
  loop:
    - 497799835  # Xcode
    - 441258766  # Magnet
    - 1295203466  # Microsoft Remote Desktop
    - 424390742  # Compressor
    - 424389933  # Final Cut Pro
    - 409183694  # Keynote
    - 434290957  # Motion
    - 409203825  # Numbers
    - 409201541  # Pages
    - 1569813296  # 1Password for Safari
    - 1440147259  # AdGuard for Safari
    - 1573461917  # SponsorBlock for YouTube
    - 1521133201  # Speed Player for Safari
