---
# Homebrew packages
- name: Install homebrew packages.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
    upgrade_all: "{{ package_install_latest }}"
  loop:
    - "dockutil"
    - "doctl"
    - "fastfetch"
    - "mas"
    - "neovim"
    - "pyenv"
    - "zbar"
  when: false

# Homebrew casks
- name: Install homebrew casks.
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    update_homebrew: true
    upgrade_all: "{{ package_install_latest }}"
  loop:
    # Fonts
    - "font-meslo-lg-nerd-font"
    # General
    - "1password"
    - "alacritty"
    - "arc"
    # - "mullvadvpn"
    # - "obsidian"
    # - "signal"
    # - "slack"
    # - "spotify"
    # Development
    # - "db-browser-for-sqlite"
    # - "devtoys"
    # - "docker"
    # - "dotnet-sdk"
    # - "github"
    # - "iterm2"
    # - "parallels"  # For this `Privacy and Security` -> `App Management` -> `Terminal` has to be enabled.
    # - "postman"
    # - "raspberry-pi-imager"
    # - "sublime-text"
    # - "vagrant-vmware-utility"
    # - "vagrant"
    # - "visual-studio-code"
    # - "vmware-fusion"
    # - "vnc-viewer"
    # - "wezterm"
    # Utility
    # - "aldente"
    # - "appcleaner"
    # - "betterdisplay"
    # - "hiddenbar"
    # - "keyboardcleantool"
    # - "obs"
    # - "openinterminal"
    # - "raycast"
    # - "scroll-reverser"
    # - "synology-drive"
    # - "vlc"
    # Creative
    # - "affinity-designer"
    # - "affinity-photo"
    # - "affinity-publisher"
    # - "updf"
  tags:
    - ignore-vm

# App Store
- name: Install app store apps.  # noqa: args[module]
  community.general.mas:
    id: "{{ item | int }}"
    state: present
  loop:
    # Development
    - 497799835  # Xcode
    # Utility
    - 441258766  # Magnet
    - 1295203466  # Microsoft Remote Desktop
    # Creative
    - 424390742  # Compressor
    - 424389933  # Final Cut Pro
    - 409183694  # Keynote
    - 434290957  # Motion
    - 409203825  # Numbers
    - 409201541  # Pages
    # Safari Extensions
    - 1569813296  # 1Password for Safari
    - 1440147259  # AdGuard for Safari
    - 1573461917  # SponsorBlock for YouTube
    - 1521133201  # Speed Player for Safari
  tags:
    - ignore-vm

# Create package symlinks.
- name: Ensure symlink directories exist.
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: "0775"
  loop: "{{ package_symlinks }}"

- name: Create dotfile symlinks.
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ package_symlinks }}"
