---
# Homebrew packages
- name: Install homebrew packages.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
    upgrade_all: "{{ packages_upgrade_packages }}"
  loop:
    - "bat"
    - "dockutil"
    # - "doctl"
    - "eza"
    - "fzf"
    - "git"
    - "htop"
    - "jandedobbeleer/oh-my-posh/oh-my-posh"
    # - "jesseduffield/lazygit/lazygit"
    # - "mas"
    - "pyenv"
    - "tmux"
    # - "tree"
    # - "zbar"

# Homebrew casks
- name: Install homebrew casks.
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    update_homebrew: true
    upgrade_all: "{{ packages_upgrade_packages }}"
  loop:
    # Fonts
    - "font-hack-nerd-font"
    - "font-meslo-lg-nerd-font"
    # General
    - "1password"
    - "arc"
    - "mullvadvpn"
    - "obsidian"
    - "signal"
    - "slack"
    - "spotify"
    # Development
    - "alacritty"
    # - "db-browser-for-sqlite"
    - "devtoys"
    - "docker"
    - "dotnet-sdk"
    - "github"
    - "iterm2"
    # - "parallels"  # For this `Privacy and Security` -> `App Management` -> `Terminal` has to be enabled.
    - "postman"
    - "raspberry-pi-imager"
    - "sublime-text"
    - "vagrant-vmware-utility"
    - "vagrant"
    - "visual-studio-code"
    - "vmware-fusion"
    - "vnc-viewer"
    # Utility
    - "aldente"
    - "appcleaner"
    - "betterdisplay"
    - "hiddenbar"
    - "keyboardcleantool"
    - "obs"
    - "openinterminal"
    - "raycast"
    - "scroll-reverser"
    - "synology-drive"
    - "vlc"
    # Creative
    - "affinity-designer"
    - "affinity-photo"
    - "affinity-publisher"
    - "updf"
  tags:
    - ignore-vm

# App Store
- name: Install app store apps.  # noqa: args[module]
  community.general.mas:
    id: "{{ item | int }}"
    state: present
  loop:
    # Development
    - 497799835  # Xcode
    # Utility
    - 441258766  # Magnet
    - 1295203466  # Microsoft Remote Desktop
    # Creative
    - 424390742  # Compressor
    - 424389933  # Final Cut Pro
    - 409183694  # Keynote
    - 434290957  # Motion
    - 409203825  # Numbers
    - 409201541  # Pages
    # Safari Extensions
    - 1569813296  # 1Password for Safari
    - 1440147259  # AdGuard for Safari
    - 1573461917  # SponsorBlock for YouTube
    - 1521133201  # Speed Player for Safari
  tags:
    - ignore-vm

# Oh My Zsh
- name: Download ohmyzsh installer.
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "/tmp/ohmyzsh_install.sh"
    mode: "755"

- name: Run ohmyzsh installer.
  ansible.builtin.command: >
    /tmp/ohmyzsh_install.sh
  args:
    creates: "${HOME}/.oh-my-zsh"
  environment:
    RUNZSH: "no"
    CHSH: "no"

- name: Install zsh-autosuggestions.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

# Compare installed packages with Brewfile
- name: Make sure all brewfile packages are installed.  # noqa: ignore-errors
  ansible.builtin.command: >
    brew bundle check --file=${HOME}/macos-setup/brew/Brewfile
  changed_when: false
  ignore_errors: true
  tags:
    - ignore-vm
