---
- name: Set system appearance to dark
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    value: Dark
    type: string

- name: Enable battery percentage
  community.general.osx_defaults:
    domain: com.apple.controlcenter.plist
    key: BatteryShowPercentage
    value: true
    type: bool

- name: Do not create .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    value: 'true'
    type: string

- name: Disable desktop reveal by clicking wallpaper
  community.general.osx_defaults:
    domain: com.apple.WindowManager
    key: EnableStandardClickToShowDesktop
    value: 0
    type: int
