---
- name: Install zsh on Linux.
  community.general.homebrew:
    name: "zsh"
    state: "{{ 'latest' if package_install_latest else 'present' }}"
    update_homebrew: true
  when: ansible_os_family != "Darwin"

- name: Install terminal packages.
  community.general.homebrew:
    name: "{{ item }}"
    state: "{{ 'latest' if package_install_latest else 'present' }}"
    update_homebrew: true
  loop:
    - "bat"
    - "eza"
    - "fastfetch"
    - "fzf"
    - "git"
    - "htop"
    - "lazygit"
    - "neovim"
    - "oh-my-posh"
    - "pyenv"
    - "tmux"
    - "tree"

# Oh My Zsh
- name: Download ohmyzsh installer.
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "/tmp/ohmyzsh-install.sh"
    mode: "0755"

- name: Run ohmyzsh installer.
  ansible.builtin.command: >
    /tmp/ohmyzsh-install.sh
  args:
    creates: "${HOME}/.oh-my-zsh"
  environment:
    RUNZSH: "no"
    CHSH: "no"

- name: Install fzf-tab.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/Aloxaf/fzf-tab"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/fzf-tab"

- name: Install zsh-autosuggestions.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install tmux plugin manager.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "${HOME}/.tmux/plugins/tpm"

# Create terminal symlinks.
- name: Ensure symlink directories exist.
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: "0775"
  loop: "{{ terminal_symlinks }}"

- name: Create dotfile symlinks.
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ terminal_symlinks }}"
