---
- name: Install terminal packages.
  community.general.homebrew:
    name: "{{ item }}"
    state: "{{ 'latest' if package_install_latest else 'present' }}"
    update_homebrew: true
  loop:
    - "bat"
    - "eza"
    - "fzf"
    - "git"
    - "htop"
    - "jesseduffield/lazygit/lazygit"
    - "oh-my-posh"
    - "tmux"
    - "tree"
    - "zsh"

# - name: Get username.
#   ansible.builtin.command: >
#     whoami
#   become: false
#   changed_when: false
#   register: username

# - name: Get zsh path.
#   ansible.builtin.command: >
#     brew --prefix zsh
#   changed_when: false
#   register: zsh_path

# - name: Set zsh as default shell.
#   ansible.builtin.user:
#     name: "{{ username.stdout }}"
#     shell: "{{ zsh_path.stdout }}"
#   become: true

# Oh My Zsh
- name: Download ohmyzsh installer.
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "/tmp/ohmyzsh_install.sh"
    mode: "0755"

- name: Run ohmyzsh installer.
  ansible.builtin.command: >
    /tmp/ohmyzsh_install.sh
  args:
    creates: "${HOME}/.oh-my-zsh"
  environment:
    RUNZSH: "no"
    CHSH: "no"

- name: Install fzf-tab.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/Aloxaf/fzf-tab"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/fzf-tab"

- name: Install zsh-autosuggestions.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install tmux plugin manager.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "${HOME}/.tmux/plugins/tpm"

# Create terminal symlinks.
- name: Ensure symlink directories exist.
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: "0775"
  loop: "{{ terminal_symlinks }}"

- name: Create dotfile symlinks.
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ terminal_symlinks }}"
