---
- name: Install zsh on Linux.
  community.general.homebrew:
    name: "zsh"
    state: present
    update_homebrew: true
  when: ansible_os_family != "Darwin"

- name: Update homebrew index.
  community.general.homebrew:
    update_homebrew: true

- name: Install terminal packages.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - "bat"
    - "eza"
    - "fastfetch"
    - "git"
    - "htop"
    - "lazydocker"
    - "lazygit"
    - "neovim"
    - "oh-my-posh"
    - "pyenv"
    - "tmux"
    - "tree"

    # https://yazi-rs.github.io/docs/installation
    - "yazi"
    - "sevenzip"
    - "jq"
    - "poppler"
    - "fd"
    - "ripgrep"
    - "fzf"
    - "zoxide"
    - "imagemagick"
    - "ffmpegthumbnailer"

- name: Install nerd font macOS.
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - "font-meslo-lg-nerd-font"
    - "font-symbols-only-nerd-font"
  when: ansible_os_family == "Darwin"

- name: Upgrade homebrew packages.
  community.general.homebrew:
    upgrade_all: true
  when: package_install_latest

# Oh My Zsh
- name: Download ohmyzsh installer.
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "/tmp/ohmyzsh-install.sh"
    mode: "0755"

- name: Run ohmyzsh installer.
  ansible.builtin.command: >
    /tmp/ohmyzsh-install.sh
  args:
    creates: "${HOME}/.oh-my-zsh"
  environment:
    RUNZSH: "no"
    CHSH: "no"

- name: Install fzf-tab.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/Aloxaf/fzf-tab"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/fzf-tab"

- name: Install zsh-autosuggestions.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install tmux plugin manager.  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "${HOME}/.tmux/plugins/tpm"

- name: Create config directory for bat.
  ansible.builtin.file:
    path: "${HOME}/.config/bat/themes"
    state: directory
    mode: "0755"

- name: Install catppuccin theme for bat.  # noqa: latest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
    dest: "${HOME}/.config/bat/themes/Catppuccin Mocha.tmTheme"
    mode: "0755"

- name: Rebuild bat's cache.
  ansible.builtin.command: >
    bat cache --build
  args:
    creates: "${HOME}/.cache/bat"

- name: Create config directory for yazi.
  ansible.builtin.file:
    path: "${HOME}/.config/yazi/flavors"
    state: directory
    mode: "0755"

- name: Install catppuccin-mocha theme for yazi.
  ansible.builtin.command: >
    ya pack -a yazi-rs/flavors:catppuccin-mocha
  args:
    creates: "${HOME}/.config/yazi/flavors/catppuccin-mocha.yazi/flavor.toml"

# Create terminal symlinks.
- name: Ensure symlink directories exist.
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: "0775"
  loop: "{{ terminal_symlinks }}"

- name: Create dotfile symlinks.
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ terminal_symlinks }}"
