[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
# startup_mode = "Maximized"
padding.x = 10
padding.y = 10

[font]
size = 14
normal.family = "MesloLGS Nerd Font Mono"

[keyboard]
bindings = [
    { key = "h", mods = "Alt", chars = "\u001BB" },
    { key = "j", mods = "Alt", chars = "\u001B[B" },
    { key = "k", mods = "Alt", chars = "\u001B[A" },
    { key = "l", mods = "Alt", chars = "\u001BF" },
]
