[env]
TERM = "xterm-256color"

[window]
decorations = "full"
# startup_mode = "Maximized"
padding.x = 10
padding.y = 10

[font]
size = 14
normal.family = "MesloLGS Nerd Font Mono"

[keyboard]
bindings = [
    { key = "n", mods = "Command", action = "CreateNewWindow" },
    # Navigation
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "Right", mods = "Alt", chars = "\u001BF" },
]
