select = ["ALL"]
line-length = 120
src = ["src", "tests"]
ignore = [
    "D203",  # one-blank-line-before-class
    "D212",  # multi-line-summary-first-line
    "FIX",   # flake8-fixme
    "INP",   # flake8-no-pep420
    "S104",  # hardcoded-bind-all-interfaces
    "TD002", # missing-todo-author
    "TD003", # missing-todo-link
]
[per-file-ignores]
"tests/**/*.py" = [
    "PLR2004", # magic-value-comparison
    "S101",    # assert
]
[pydocstyle]
convention = "google"
