---
- name: Setup system
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars.yml

  tasks:
    - name: Import tasks
      ansible.builtin.import_tasks:
        file: "{{ platform }}/{{ task_name }}.yml"
