---
- name: Setup system
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars:
    install_latest_packages: true

  tasks:
    - name: Import tasks
      ansible.builtin.import_tasks:
        file: "{{ platform }}/{{ task_name }}.yml"
