---
- name: Setup system
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    install_latest_packages: true

  tasks:
    - name: Import tasks
      ansible.builtin.import_tasks:
        file: "{{ task_name }}.yml"
