---
package_install_latest: false

terminal_symlinks:
  # git
  - source: ${HOME}/macos-setup/dotfiles/git/.gitconfig
    dest: ${HOME}/.gitconfig
  - source: ${HOME}/macos-setup/dotfiles/git/.gitignore_global
    dest: ${HOME}/.gitignore_global
  - source: ${HOME}/macos-setup/dotfiles/git/.gitmessage
    dest: ${HOME}/.gitmessage

  # oh-my-posh
  - source: ${HOME}/macos-setup/dotfiles/config/oh-my-posh/oh-my-posh.toml
    dest: ${HOME}/.config/oh-my-posh/oh-my-posh.toml

  # tmux
  - source: ${HOME}/macos-setup/dotfiles/config/tmux/.tmux.conf
    dest: ${HOME}/.config/tmux/tmux.conf

  # zsh
  # - source: ${HOME}/macos-setup/dotfiles/shell/.zshenv
  #   dest: ${HOME}/.zshenv
  - source: ${HOME}/macos-setup/dotfiles/shell/.zshrc
    dest: ${HOME}/.zshrc

package_symlinks:
  # sublime
  - source: ${HOME}/macos-setup/dotfiles/sublime/Preferences.sublime-settings
    dest: ${HOME}/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings

  # vscode
  - source: ${HOME}/macos-setup/dotfiles/vscode/settings.json
    dest: ${HOME}/Library/Application Support/Code/User/settings.json

  # wezterm
  - source: ${HOME}/macos-setup/dotfiles/config/wezterm/wezterm.lua
    dest: ${HOME}/.config/wezterm/wezterm.lua
