name: CI
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  molecule:
    if: false
    uses: daniel-mizsak/workflows/.github/workflows/molecule.yml@main
    with:
      os: macos-latest
      python-version: "3.10"
      yamllint: true
      yamllint-config: molecule/default/.yamllint
      ansible-lint: true
