name: CI
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  molecule:
    uses: daniel-mizsak/workflows/.github/workflows/molecule.yml@main
    with:
      os: ubuntu-latest
      working-directory: ./ansible
      python-version: 3.12
      molecule: false
      yamllint: true
      yamllint-config: .yamllint.yml
      ansible-lint: true
      ansible-lint-config: .ansible-lint.yml
